# vim: sw=4 ts=4 et ai tw=80
options:
    # http://wiki.apache.org/cassandra/FAQ#ports
    jmx-port:
        type: int
        default: 7199
        description: JMX management port
    cluster-port:
        type: int
        default: 7000
        description: Cluster communication port
    client-port:
        type: int
        default: 9160
        description: Thrift clients port
    cluster-name:
        type: string
        default: "Cassandra Cluster"
        description: >
            Name of the Cassandra Cluster - don't change yet!
    num-tokens:
        type: int
        default: 256
        description: >
            Number of tokens per node for Cassandra 1.2+. Ignored for earlier
            versions.
    auto-memory:
        type: boolean
        default: true
        description: >
            Automatically configure memory options based on specification
            of the server infrastructure its running on.
    heap-size:
        type: string
        default: 1G
        description: >
            Total size of Java memory heap, for example 1G or 512M.
            Only used if auto-memory = false.
    new-gen-size:
        type: string
        default: 100M
        description: >
            Size of Java new generation memory, for example 100M.  Only used
            if auto-memory = false.
    compaction-throughput:
        type: int
        default: 16
        description: >
            Throttles compaction to the given total throughput (in MB/sec)
            across the entire system. The faster you insert data, the faster
            you need to compact in order to keep the sstable count down,
            but in general, setting this to 16 to 32 times the rate you
            are inserting data is more than sufficient.  Setting this to
            0 disables throttling. Note that this account for all types
            of compaction, including validation compaction.
    apt-repo-spec:
        type: string
        default: deb http://www.apache.org/dist/cassandra/debian 12x main
        description: >
            Apt repository to install cassandra package(s) from.
    apt-repo-key:
        type: string
        default: 4BD736A82B5C1B00
        description: >
            Apt repository key, typically needed for apt-repo-spec.
    #------------------------------------------------------------------------
    # Volume management
    #   volume-map, volume-dev_regexp are only used 
    #   if volume-ephemeral-storage == False
    #------------------------------------------------------------------------
    volume-ephemeral-storage:
        type: boolean
        default: True
        description: |
            If False, a configure-error state will be raised if
               volume-map[$JUJU_UNIT_NAME] is not set (see "volume-map"
               below) - see "volume-map" below.
            If True, service units won't try to use "volume-map" (and
               related variables) to mount and use external (EBS) volumes,
               thus storage lifetime will equal VM, thus ephemeral.
               YOU'VE BEEN WARNED.
            
    volume-map:
        type: string
        default: ""
        description: >
            YAML map as e.g. "{ cassandra/0: vol-0000010, cassandra/1: vol-0000016 }".
            Service units will raise a "configure-error" condition if no volume-map
            value is set for it - it's expected a human to set it properly to resolve it.

    volume-dev-regexp:
        type: string
        default: "/dev/vd[b-z]"
        description: >
            Block device for attached volumes as seen by the VM, will be "scanned"
            for an unused device when "volume-map" is valid for the unit.
