# vim: sw=4 ts=4 et ai tw=80
options:
    # http://wiki.apache.org/cassandra/FAQ#ports
    allow-single-node:
        type: boolean
        default: False
        description: Allow cassandra to start in a single-node configuration.
            When deploying a new service with more than one initial unit (i.e.
            juju deploy -n 2), this should be set to false.
    jmx-port:
        type: int
        default: 7199
        description: JMX management port
    cluster-port:
        type: int
        default: 7000
        description: Cluster communication port
    client-port:
        type: int
        default: 9160
        description: Thrift clients port
    cluster-name:
        type: string
        default: "Cassandra Cluster"
        description: >
            Name of the Cassandra Cluster - don't change yet!
    num-tokens:
        type: int
        default: 256
        description: >
            Number of tokens per node for Cassandra 1.2+. Ignored for earlier
            versions.
    auto-memory:
        type: boolean
        default: true
        description: >
            Automatically configure memory options based on specification
            of the server infrastructure its running on.
    heap-size:
        type: string
        default: 1G
        description: >
            Total size of Java memory heap, for example 1G or 512M.
            Only used if auto-memory = false.
    new-gen-size:
        type: string
        default: 100M
        description: >
            Size of Java new generation memory, for example 100M.  Only used
            if auto-memory = false.
    compaction-throughput:
        type: int
        default: 16
        description: >
            Throttles compaction to the given total throughput (in MB/sec)
            across the entire system. The faster you insert data, the faster
            you need to compact in order to keep the sstable count down,
            but in general, setting this to 16 to 32 times the rate you
            are inserting data is more than sufficient.  Setting this to
            0 disables throttling. Note that this account for all types
            of compaction, including validation compaction.
    apt-repo-spec:
        type: string
        default: deb http://www.apache.org/dist/cassandra/debian 12x main
        description: >
            Apt repository to install cassandra package(s) from.
    apt-repo-key:
        type: string
        default: 4BD736A82B5C1B00
        description: >
            Apt repository key, typically needed for apt-repo-spec.
    force-seed-nodes:
        type: string
        default: ""
        description: >
            A comma separated list of seed nodes. This is useful if the cluster
            being created in this juju environment is part of a larger cluser
            and the seed nodes are remote.
    token-map-by-unitname:
        type: string
        default: ""
        description: >
            YAML map as e.g. "{ cassandra/0: 107950406921370402326527496543482482275, cassandra/1: 150485702786487710259449322472453508707 }".
            Set initial_token according to the unit name using this map. Cannot be used  if token-map-by-volid is also set. If persistent storage
            is being used then use token-map-by-volid instead.
            Useful when rebalancing a ring by hand
    token-map-by-volid:
        type: string
        default: ""
        description: >
            YAML map as e.g. "{ vol-00000012: 107950406921370402326527496543482482275, vol-00000013: 150485702786487710259449322472453508707 }".
            Set initial_token according to the name of the attached volume using this map. Can only be used when using persistent storage
            and cannot be used if token-map-by-unitname is also set. 
            Useful when rebalancing a ring by hand
    #------------------------------------------------------------------------
    # Volume management
    #   volume-map, volume-dev_regexp are only used 
    #   if volume-ephemeral-storage == False
    #------------------------------------------------------------------------
    volume-ephemeral-storage:
        type: boolean
        default: True
        description: |
            If False, a configure-error state will be raised if
               volume-map[$JUJU_UNIT_NAME] is not set (see "volume-map"
               below) - see "volume-map" below.
            If True, service units won't try to use "volume-map" (and
               related variables) to mount and use external (EBS) volumes,
               thus storage lifetime will equal VM, thus ephemeral.
               YOU'VE BEEN WARNED.
            
    volume-map:
        type: string
        default: ""
        description: >
            YAML map as e.g. "{ cassandra/0: vol-0000010, cassandra/1: vol-0000016 }".
            Service units will raise a "configure-error" condition if no volume-map
            value is set for it - it's expected a human to set it properly to resolve it.

    volume-dev-regexp:
        type: string
        default: "/dev/vd[b-z]"
        description: >
            Block device for attached volumes as seen by the VM, will be "scanned"
            for an unused device when "volume-map" is valid for the unit.
    nagios_context:
        default: "juju"
        type: string
        description: |
            a string that will be prepended to instance name to set the host name
            in nagios. So for instance the hostname would be something like:
                juju-cassandra-0
            If you're running multiple environments with the same services in them
            this allows you to differentiate between them.
    nagios_heapchk_warn_pct:
        default: 80
        type: int
        description: |
            The pct of heap used to trigger a nagios warning
    nagios_heapchk_crit_pct:
        default: 90
        type: int
        description: |
            The pct of heap used to trigger a nagios critcal alert

    extra_packages:
	type: string
	default: ""
	description: |
            Extra packages to install. A space delimited list of packages.

